#!/bin/bash -eu

cd "$(dirname "$0")"
cd ../..

if ! which sudo;
then
    # e.g. CI doesn't have it..
    function sudo {
        "$@"
    }
fi

# TODO think if we really want to guard it by this if..
if [ -v CI ]; then
    sudo apt update
    # TODO use some other docs in /usr/local/share?
    sudo apt install python3-doc
fi

pip3 install --user tox
tox
